services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: azechum
      POSTGRES_PASSWORD: pros14526@
      POSTGRES_DB: npresecdb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres_data:
